name: Deploy to Ambulance Server

on:
    push:
        branches:
            - dev
        paths:
            - "amb/**"

jobs:
    ambulance_deploy:
        runs-on: ubuntu-20.04
        defaults:
            run:
                working-directory: amb

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Install node lts
              run: |
                  export NVM_DIR="$HOME/.nvm"
                  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
                  nvm install --lts

            - name: Make Dot ENV
              run: |
                  echo "${ENV}" > .env
              env:
                  ENV: ${{ secrets.AMBULANCE_ENV }}

            - name: Install Dependencies & Test
              run: |
                  npm install
                  npm run test

            - name: Build
              run: |
                  npm run build

            - name: SCP
              uses: appleboy/scp-action@master
              with:
                  host: ${{secrets.AMBULANCE_SERVER}}
                  username: ${{secrets.USERNAME}}
                  key: ${{secrets.AMBULANCE_SERVER_PRIVATE_KEY}}
                  source: "amb/build"
                  target: "www"
                  strip_components: 1
